### ISSUE TITLE
Don't Starve get freezed screen on the game start menu

### ISSUE THREAD

**Issue by kukusyaoran** [Rinnegatamante/rinCheat#18]
The plugin will cause the game freeze at the start menu, any button doesn't work with game music still on. After I disabled the plugin in game.txt, the game works.

**Comment by Rinnegatamante** [comment]
Should be fixed in next release (it should came in next days). Please report the results with the incoming version of the plugin.

**Comment by kukusyaoran** [comment]
@Rinnegatamante The version I tested is rinCheat beta4.

**Comment by Rinnegatamante** [comment]
Try with the stable release version ( can be found on GekiHEN contest website).

**Comment by kukusyaoran** [comment]
@Rinnegatamante I just test the version from GekiHEN（which is v.0.1 Stable），but still get the same issue. I don't know how to bebug this in more detail, so thanks anyway for your hard work.
